import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import SearchButton from './components/SearchButton'
import { clothingData } from '../utils/ClothingData'; // Import the clothing data
import ClothingItem from './components/ClothingItem'
import ClothesList from './components/ClothesList'
import { Afacad } from 'next/font/google'

const afacad = Afacad({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="description"  />
        {/* Add other meta tags, stylesheets, or scripts here */}
      </head>
      <body className={afacad.className}>
        <Navbar />
        
        {children}
      </body>
    </html>
  );
}
